server {
    listen 80;
    server_name 127.0.0.1;

    proxy_set_header Host $host;

    root /usr/share/nginx/html;
    index index.php index.html;

    client_max_body_size 1G;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php(?:$|/) {

        include fastcgi_params;

        fastcgi_split_path_info ^(.+\.php)(/.*)$;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $host;

        fastcgi_index index.php;

        fastcgi_pass php:9000;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|svg|woff|woff2|ttf)$ {
        expires 30d;
        access_log off;
    }

    location ~ /\. {
        deny all;
    }
}